// GENERATED by tools/gen_counters.py from shared/exercises.json — do not edit.
#pragma once
#include "rep_counter.h"

// Per-movement default CounterConfig, indexed by watch_movement_id.
// { kind, axis_mode, lp_ms, hp_ms, thr_pct, min_rep_ms, min_amp, warmup_ms }
static const CounterConfig COUNTER_CONFIGS[] = {
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 0 Custom
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 1 Bench Press
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 2 Incline Press
  {0, 1, 500, 3000, 30, 900, 60, 700},  // 3 Overhead Press
  {0, 3, 500, 3000, 30, 900, 70, 700},  // 4 Push-up
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 5 Dip
  {0, 4, 500, 3000, 40, 800, 150, 0},  // 6 Lateral Raise
  {0, 4, 500, 3000, 40, 700, 150, 0},  // 7 Biceps Curl
  {0, 4, 500, 3000, 40, 700, 150, 0},  // 8 Hammer Curl
  {0, 4, 500, 3000, 40, 700, 150, 0},  // 9 Triceps Extension
  {0, 4, 500, 3000, 40, 700, 150, 0},  // 10 Triceps Pushdown
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 11 Barbell Row
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 12 Dumbbell Row
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 13 Lat Pulldown
  {0, 4, 500, 3000, 40, 1100, 150, 0},  // 14 Pull-up
  {0, 4, 500, 3000, 40, 1100, 150, 0},  // 15 Chin-up
  {0, 4, 500, 3000, 40, 700, 150, 0},  // 16 Shrug
  {0, 4, 500, 3000, 40, 1200, 150, 0},  // 17 Deadlift
  {0, 4, 500, 3000, 40, 1100, 150, 0},  // 18 Romanian Deadlift
  {0, 4, 500, 3000, 40, 1100, 150, 0},  // 19 Squat
  {0, 4, 500, 3000, 40, 1100, 150, 0},  // 20 Front Squat
  {0, 4, 500, 3000, 40, 1000, 150, 0},  // 21 Goblet Squat
  {0, 4, 500, 3000, 40, 1000, 150, 0},  // 22 Lunge
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 23 Leg Press
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 24 Leg Curl
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 25 Leg Extension
  {0, 4, 500, 3000, 40, 600, 150, 0},  // 26 Calf Raise
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 27 Hip Thrust
  {0, 4, 500, 3000, 40, 600, 150, 0},  // 28 Kettlebell Swing
  {0, 4, 500, 3000, 40, 700, 150, 0},  // 29 Crunch
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 30 Plank
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 31 L-sit
  {0, 4, 500, 3000, 40, 600, 150, 0},  // 32 Russian Twist
  {0, 4, 500, 3000, 40, 800, 150, 0},  // 33 Face Pull
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 34 Ring Row
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 35 Ring Support Hold
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 36 Pike Push-up
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 37 Hollow-body Hold
  {0, 4, 500, 3000, 40, 1200, 150, 0},  // 38 Dead Bug
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 39 Tuck Front Lever
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 40 German Hang
  {0, 4, 500, 3000, 40, 1000, 150, 0},  // 41 Bulgarian Split Squat
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 42 Dead Hang
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 43 Planche Lean
  {0, 4, 500, 3000, 40, 1000, 150, 0},  // 44 Pseudo-planche Push-up
  {0, 4, 500, 3000, 40, 600, 150, 0},  // 45 Hollow Rock
  {0, 4, 500, 3000, 40, 900, 150, 0},  // 46 Side Plank
  {0, 4, 500, 3000, 40, 1200, 150, 0},  // 47 Pistol Squat
};

#define COUNTER_CONFIG_COUNT (sizeof COUNTER_CONFIGS / sizeof COUNTER_CONFIGS[0])

// Movement's config, or Custom (0) as a safe fallback for unknown ids.
static inline const CounterConfig *counter_config_for(uint8_t movement_id) {
  return movement_id < COUNTER_CONFIG_COUNT ? &COUNTER_CONFIGS[movement_id]
                                            : &COUNTER_CONFIGS[0];
}
