// GENERATED by tools/gen_movements.py from shared/exercises.json — do not edit.
#pragma once
#include <stdint.h>

typedef struct {
  const char *name;
  uint16_t min_rep_ms;   // refractory period for the rep counter
  uint8_t smoothing;     // moving-average taps
  uint8_t default_timed;
} MovementInfo;

static const MovementInfo MOVEMENTS[] = {
  {"Custom", 900, 5, 0},  // 0
  {"Bench Press", 900, 5, 0},  // 1
  {"Incline Press", 900, 5, 0},  // 2
  {"Overhead Press", 900, 5, 0},  // 3
  {"Push-up", 900, 5, 0},  // 4
  {"Dip", 900, 5, 0},  // 5
  {"Lateral Raise", 800, 5, 0},  // 6
  {"Biceps Curl", 700, 5, 0},  // 7
  {"Hammer Curl", 700, 5, 0},  // 8
  {"Triceps Extension", 700, 5, 0},  // 9
  {"Triceps Pushdown", 700, 5, 0},  // 10
  {"Barbell Row", 900, 5, 0},  // 11
  {"Dumbbell Row", 900, 5, 0},  // 12
  {"Lat Pulldown", 900, 5, 0},  // 13
  {"Pull-up", 1100, 5, 0},  // 14
  {"Chin-up", 1100, 5, 0},  // 15
  {"Shrug", 700, 5, 0},  // 16
  {"Deadlift", 1200, 5, 0},  // 17
  {"Romanian Deadlift", 1100, 5, 0},  // 18
  {"Squat", 1100, 5, 0},  // 19
  {"Front Squat", 1100, 5, 0},  // 20
  {"Goblet Squat", 1000, 5, 0},  // 21
  {"Lunge", 1000, 5, 0},  // 22
  {"Leg Press", 900, 5, 0},  // 23
  {"Leg Curl", 900, 5, 0},  // 24
  {"Leg Extension", 900, 5, 0},  // 25
  {"Calf Raise", 600, 5, 0},  // 26
  {"Hip Thrust", 900, 5, 0},  // 27
  {"Kettlebell Swing", 600, 5, 0},  // 28
  {"Crunch", 700, 5, 0},  // 29
  {"Plank", 900, 5, 1},  // 30
  {"L-sit", 900, 5, 1},  // 31
  {"Russian Twist", 600, 5, 0},  // 32
  {"Face Pull", 800, 5, 0},  // 33
  {"Ring Row", 900, 5, 0},  // 34
  {"Ring Support Hold", 900, 5, 1},  // 35
  {"Pike Push-up", 900, 5, 0},  // 36
  {"Hollow-body Hold", 900, 5, 1},  // 37
  {"Dead Bug", 1200, 5, 0},  // 38
  {"Tuck Front Lever", 900, 5, 1},  // 39
  {"German Hang", 900, 5, 1},  // 40
  {"Bulgarian Split Squat", 1000, 5, 0},  // 41
  {"Dead Hang", 900, 5, 1},  // 42
  {"Planche Lean", 900, 5, 1},  // 43
  {"Pseudo-planche Push-up", 1000, 5, 0},  // 44
  {"Hollow Rock", 600, 5, 0},  // 45
  {"Side Plank", 900, 5, 1},  // 46
  {"Pistol Squat", 1200, 5, 0},  // 47
};

#define MOVEMENT_COUNT (sizeof MOVEMENTS / sizeof MOVEMENTS[0])

static inline const char *movement_name(uint8_t id) {
  return id < MOVEMENT_COUNT ? MOVEMENTS[id].name : "Unknown";
}
