#!/usr/bin/env python3
"""Generate src/c/movements.h from shared/exercises.json.

Run from the repo root after editing the seed:  python3 tools/gen_movements.py
"""
import json
import pathlib

root = pathlib.Path(__file__).resolve().parents[1]
seed = json.loads((root / "shared" / "exercises.json").read_text())
exercises = sorted(seed["exercises"], key=lambda e: e["id"])

ids = [e["id"] for e in exercises]
assert ids == list(range(len(ids))), "watch_movement_ids must be contiguous from 0"

lines = [
    "// GENERATED by tools/gen_movements.py from shared/exercises.json — do not edit.",
    "#pragma once",
    "#include <stdint.h>",
    "",
    "typedef struct {",
    "  const char *name;",
    "  uint16_t min_rep_ms;   // refractory period for the rep counter",
    "  uint8_t smoothing;     // moving-average taps",
    "  uint8_t default_timed;",
    "} MovementInfo;",
    "",
    "static const MovementInfo MOVEMENTS[] = {",
]
for e in exercises:
    profile = e.get("profile", {})
    name = e["name"].replace('"', '\\"')
    lines.append(
        '  {"%s", %d, %d, %d},  // %d'
        % (name, profile.get("min_rep_ms", 900), profile.get("smoothing", 5),
           1 if e.get("default_timed") else 0, e["id"])
    )
lines += [
    "};",
    "",
    "#define MOVEMENT_COUNT (sizeof MOVEMENTS / sizeof MOVEMENTS[0])",
    "",
    "static inline const char *movement_name(uint8_t id) {",
    '  return id < MOVEMENT_COUNT ? MOVEMENTS[id].name : "Unknown";',
    "}",
    "",
]
out = root / "src" / "c" / "movements.h"
out.write_text("\n".join(lines))
print(f"wrote {out} ({len(exercises)} movements)")
