#!/usr/bin/env python3
"""Generate src/c/embedded_workouts.h from the dev server's device API.

Dev workflow until real sync (M3): edit workouts on the dev server, then:
    python3 tools/gen_embedded.py && pebble build
Requires the server running with DEV_LOGIN=1.

Override the server with STRENGTH_SERVER, e.g.
    STRENGTH_SERVER=http://192.168.1.36:8090 python3 tools/gen_embedded.py
"""
import base64
import json
import os
import pathlib
import urllib.request

root = pathlib.Path(__file__).resolve().parents[1]
server = os.environ.get("STRENGTH_SERVER", "http://localhost:8090").rstrip("/")
url = f"{server}/api/device/workouts"
data = json.loads(urllib.request.urlopen(url, timeout=5).read())

lines = [
    "// GENERATED by tools/gen_embedded.py from the dev server — do not edit.",
    "// Packed per SPEC.md §4.2; placeholder for real AppMessage sync (M3).",
    "#pragma once",
    "#include <stdint.h>",
    "",
]
names = []
for s in data["slots"]:
    raw = base64.b64decode(s["data"])
    var = f"EMBEDDED_W{s['slot']}"
    names.append(var)
    body = ", ".join(f"0x{b:02x}" for b in raw)
    lines.append(f"// slot {s['slot']}: {s['title']} ({len(raw)} B)")
    lines.append(f"static const uint8_t {var}[] = {{ {body} }};")
    lines.append("")

lines += [
    "typedef struct { const uint8_t *data; uint16_t len; } EmbeddedWorkout;",
    "",
    "static const EmbeddedWorkout EMBEDDED_WORKOUTS[] = {",
]
for var in names:
    lines.append(f"  {{ {var}, sizeof {var} }},")
lines += [
    "};",
    "",
    "#define EMBEDDED_WORKOUT_COUNT (sizeof EMBEDDED_WORKOUTS / sizeof EMBEDDED_WORKOUTS[0])",
    "",
]
out = root / "src" / "c" / "embedded_workouts.h"
out.write_text("\n".join(lines))
print(f"wrote {out} ({len(names)} workouts)")
