#!/usr/bin/env python3
"""Generate src/c/counters.h — the compiled-in per-movement CounterConfig table
— from shared/exercises.json. This is the on-device *default* config for each
movement (tuned where we have data, sane fallbacks elsewhere); a later
device-download rail can override it at runtime.

Mirrors seed.rs: axis label -> axis_mode, and the same field defaults, so the
watch and server agree on every movement's baseline config.

  python3 tools/gen_counters.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
AXIS = {"auto": 0, "x": 1, "y": 2, "z": 3, "mag": 4, "linear": 4}
DEFAULTS = dict(axis="mag", lp_ms=500, hp_ms=3000, thr_pct=40,
                min_rep_ms=900, min_amp=150, warmup_ms=0)


def main():
    cat = json.load(open(ROOT / "shared" / "exercises.json"))["exercises"]
    by_id = {e["id"]: e for e in cat}
    n = max(by_id) + 1

    lines = [
        "// GENERATED by tools/gen_counters.py from shared/exercises.json — do not edit.",
        "#pragma once",
        '#include "rep_counter.h"',
        "",
        "// Per-movement default CounterConfig, indexed by watch_movement_id.",
        "// { kind, axis_mode, lp_ms, hp_ms, thr_pct, min_rep_ms, min_amp, warmup_ms }",
        "static const CounterConfig COUNTER_CONFIGS[] = {",
    ]
    for i in range(n):
        e = by_id.get(i)
        p = dict(DEFAULTS)
        name = "(gap)"
        if e:
            name = e["name"]
            p.update(e.get("profile", {}))
        axis_mode = AXIS.get(p["axis"], 0)
        lines.append(
            f"  {{0, {axis_mode}, {p['lp_ms']}, {p['hp_ms']}, {p['thr_pct']}, "
            f"{p['min_rep_ms']}, {int(p['min_amp'])}, {p['warmup_ms']}}},  // {i} {name}"
        )
    lines += [
        "};",
        "",
        "#define COUNTER_CONFIG_COUNT (sizeof COUNTER_CONFIGS / sizeof COUNTER_CONFIGS[0])",
        "",
        "// Compiled-in default config for a movement (Custom (0) for unknown ids).",
        "// counters_store wraps this, preferring a downloaded override when present.",
        "static inline const CounterConfig *counter_config_default(uint8_t movement_id) {",
        "  return movement_id < COUNTER_CONFIG_COUNT ? &COUNTER_CONFIGS[movement_id]",
        "                                            : &COUNTER_CONFIGS[0];",
        "}",
        "",
    ]
    out = ROOT / "src" / "c" / "counters.h"
    out.write_text("\n".join(lines))
    print(f"wrote {out} ({n} movements)")


if __name__ == "__main__":
    main()
